[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google_apis_ex = { path = "../" }
tokio = { version = "*", features = ["full"] }
gcp_auth = "*"
clap = "=3.0.0-beta.5"